# Remove version line as it's obsolete in newer Docker Compose
services:
  # Apache Jena Fuseki service
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: jena-fuseki-nutrigraph
    ports:
      - "3030:3030"
    environment:
      # Admin user credentials
      - ADMIN_PASSWORD=admin123
      # JVM options for better performance
      - JVM_ARGS=-Xmx2g -Xms1g
      # Enable CORS for web applications
      - FUSEKI_CORS=true
      # Set the base directory
      - FUSEKI_BASE=/fuseki
    volumes:
      # Persist Fuseki data and configuration
      - fuseki_data:/fuseki
      # Mount your existing knowledge graph data if available (optional)
      # - ./apache-jena-fuseki-5.4.0/run/databases:/fuseki/databases:ro
    restart: unless-stopped
    networks:
      - nutrigraph-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # REMOVED THE PROBLEMATIC COMMAND - Let Fuseki use its default startup

  # NutriGraph application
  nutrigraph:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutrigraph-app
    ports:
      - "8080:8080"
    depends_on:
      fuseki:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NUTRIGRAPH_FUSEKI_URL=http://fuseki:3030
      - NUTRIGRAPH_DATASET_NAME=african-middle-eastern-kg
      - NUTRIGRAPH_LUCENE_INDEX_PATH=/app/lucene-index-african
      - NUTRIGRAPH_IMAGES_BASE_PATH=/app/images
      # Logging levels
      - LOGGING_LEVEL_COM_NUTRIGRAPH=DEBUG
      - LOGGING_LEVEL_ORG_APACHE_JENA=WARN
    volumes:
      # Mount image data
      - ./Serializer/african_middle_eastern_data/images:/app/images:ro
      # Persist Lucene index
      - nutrigraph_index:/app/lucene-index-african
    networks:
      - nutrigraph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

networks:
  nutrigraph-network:
    driver: bridge
    name: nutrigraph-network

volumes:
  fuseki_data:
    driver: local
    name: nutrigraph_fuseki_data
  nutrigraph_index:
    driver: local
    name: nutrigraph_lucene_index