version: '3.8'

services:
  # Apache Jena Fuseki service
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: jena-fuseki-nutrigraph
    ports:
      - "3030:3030"
    environment:
      # Admin user credentials
      - ADMIN_PASSWORD=admin123
      # JVM options for better performance
      - JVM_ARGS=-Xmx2g -Xms1g
      # Enable CORS for web applications
      - FUSEKI_CORS=true
      # Set the base directory
      - FUSEKI_BASE=/fuseki
    volumes:
      # Persist Fuseki data and configuration
      - fuseki_data:/fuseki
      # Mount your existing knowledge graph data if available
      - ./apache-jena-fuseki-5.4.0/run/databases:/fuseki/databases
      # Optional: Mount any custom configuration
      - ./fuseki-config:/fuseki/config
    restart: unless-stopped
    networks:
      - nutrigraph-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030/$/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: [
      "--config=/fuseki/config/config.ttl",
      "--port=3030",
      "--localhost"
    ]

  # NutriGraph application
  nutrigraph:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutrigraph-app
    ports:
      - "8080:8080"
    depends_on:
      fuseki:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NUTRIGRAPH_FUSEKI_URL=http://fuseki:3030
      - NUTRIGRAPH_DATASET_NAME=african-middle-eastern-kg
      - NUTRIGRAPH_LUCENE_INDEX_PATH=/app/lucene-index-african
      - NUTRIGRAPH_IMAGES_BASE_PATH=/app/images
      # Database connection settings
      - SPRING_DATASOURCE_URL=sparql:http://fuseki:3030/african-middle-eastern-kg
      # Logging levels
      - LOGGING_LEVEL_COM_NUTRIGRAPH=DEBUG
      - LOGGING_LEVEL_ORG_APACHE_JENA=WARN
    volumes:
      # Mount image data
      - ./Serializer/african_middle_eastern_data/images:/app/images:ro
      # Persist Lucene index
      - nutrigraph_index:/app/lucene-index-african
    networks:
      - nutrigraph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/foods/stats || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # Optional: Database initialization service
  fuseki-init:
    image: stain/jena-fuseki:latest
    container_name: fuseki-initializer
    depends_on:
      fuseki:
        condition: service_healthy
    volumes:
      - ./apache-jena-fuseki-5.4.0/run/databases:/import-data:ro
      - fuseki_data:/fuseki
    networks:
      - nutrigraph-network
    profiles:
      - init
    command: [
      "sh", "-c", 
      "echo 'Initializing Fuseki with data...' && 
       curl -X POST http://fuseki:3030/$/datasets -H 'Content-Type: application/x-www-form-urlencoded' -d 'dbType=tdb2&dbName=african-middle-eastern-kg' &&
       echo 'Dataset created successfully' ||
       echo 'Dataset creation failed or already exists'"
    ]

networks:
  nutrigraph-network:
    driver: bridge
    name: nutrigraph-network

volumes:
  fuseki_data:
    driver: local
    name: nutrigraph_fuseki_data
  nutrigraph_index:
    driver: local
    name: nutrigraph_lucene_index