services:

  # NutriGraph application
  nutrigraph:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutrigraph-app
    ports:
      - "8080:8080"
    environment:
      - NUTRIGRAPH_FUSEKI_URL=http://host.docker.internal:3030
      - NUTRIGRAPH_DATASET_NAME=african-middle-eastern-kg
      - NUTRIGRAPH_LUCENE_INDEX_PATH=/app/lucene-index-african
      - NUTRIGRAPH_IMAGES_BASE_PATH=/app/images
    volumes:
      - ./Serializer/african_middle_eastern_data/images:/app/images
    networks:
      - nutrigraph-network

networks:
  nutrigraph-network:
    driver: bridge
